name: Python CI with uv

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: pip install uv --system

      - name: Install dependencies
        run: uv pip install -r pyproject.toml

      - name: Run tests
        run: pytest
      - name: Test with unittest
        run: |
          python -m unittest discover -s tests
